// The Scratch Project — Standard Tier Service Worker
// Cache: Standard (75 files) — v1.5 · 2026-07-21
// Generated by patch_playbooks.py for Standard build — do not manually edit

const CACHE_NAME = 'scratch-project-standard-v1-5'; // Standard-only cache — 75 files

const STATIC_FILES = [
  '/01_putting_pro.html',
  '/02_shortgame_pro.html',
  '/03_longgame_pro.html',
  '/04_complete_golfer.html',
  '/05_pre_shot_routine.html',
  '/06_golf_fitness.html',
  '/07_golf_nutrition.html',
  '/08_pro_round_prep.html',
  '/09_golf_coach_ai.html',
  '/10_scratch_plan.html',
  '/11_shot_dispersion.html',
  '/12_rules_of_golf.html',
  '/13_injury_prevention.html',
  '/14_video_analysis.html',
  '/15_equipment_fitting.html',
  '/16_solo_pressure_round.html',
  '/17_progress_journal.html',
  '/18_training_aids_2.html',
  '/19_swing_mechanics.html',
  '/20_course_management.html',
  '/21_mental_game.html',
  '/22_wedge_distances.html',
  '/23_weather_conditions.html',
  '/24_competitive_strategy.html',
  '/25_speed_training.html',
  '/26_stats_interpretation.html',
  '/27_six_month_plan.html',
  '/28_months_7_12_plan.html',
  '/29_months_13_18_plan.html',
  '/30_months_19_24_plan.html',
  '/31_on_course_notes.html',
  '/33_competitive_pathway.html',
  '/34_coaching_relationship.html',
  '/35_links_travel_golf.html',
  '/36_playing_partners.html',
  '/37_approach_zone.html',
  '/404.html',
  '/50_links_golf_strategy.html',
  '/52_matchplay_formats.html',
  '/58_bunker_play.html',
  '/59_practice_green_protocol.html',
  '/60_100_ball_session.html',
  '/61_short_game_lies.html',
  '/62_grip_tension.html',
  '/63_tracking_choice.html',
  '/64_range_setup.html',
  '/70_grip_fundamentals.html',
  '/71_money_games.html',
  '/72_equipment_decode.html',
  '/73_course_architecture.html',
  '/_preview_dual_tables.html',
  '/_preview_hybrid_table.html',
  '/b1_starting_golf.html',
  '/b2_first_swings.html',
  '/b3_short_game_first.html',
  '/b4_first_rounds.html',
  '/b5_getting_handicap.html',
  '/b6_road_to_24.html',
  '/expected_score.html',
  '/hcp_trajectory.html',
  '/index.html',
  '/journal_templates.html',
  '/motivation.html',
  '/on_course_reference_A5_8pp.html',
  '/playing_hcp_calculator.html',
  '/privacy.html',
  '/quick_start.html',
  '/sg_diagnostic.html',
  '/swing_fault_finder.html',
  '/terms.html',
  '/wind_calculator.html',
  '/manifest.json',
  '/scratch_profile.js',
  '/icon192.png',
  '/icon512.png',
];

// Install: cache all static files
self.addEventListener('install', function(event) {
  event.waitUntil(
    caches.open(CACHE_NAME).then(function(cache) {
      console.log('[SW] Installing v1.5 — caching', STATIC_FILES.length, 'files');
      return Promise.all(
        STATIC_FILES.map(function(url) {
          return cache.add(url).catch(function(err) {
            console.warn('[SW] Failed to cache:', url, err);
          });
        })
      );
    }).then(function() {
      console.log('[SW] Install complete — v1.5');
      return self.skipWaiting();
    })
  );
});

// Activate: delete old caches
self.addEventListener('activate', function(event) {
  event.waitUntil(
    caches.keys().then(function(keys) {
      return Promise.all(
        keys.filter(function(key) {
          return key !== CACHE_NAME;
        }).map(function(key) {
          console.log('[SW] Deleting old cache:', key);
          return caches.delete(key);
        })
      );
    }).then(function() {
      console.log('[SW] Activated — v1.5 is current cache');
      return self.clients.claim();
    })
  );
});

// Fetch: cache-first with network fallback
self.addEventListener('fetch', function(event) {
  // Only handle GET requests for same-origin resources
  if (event.request.method !== 'GET') return;

  event.respondWith(
    caches.match(event.request).then(function(cached) {
      if (cached) {
        return cached;
      }
      return fetch(event.request).then(function(response) {
        // Cache successful responses
        if (response && response.status === 200 && response.type === 'basic') {
          var clone = response.clone();
          caches.open(CACHE_NAME).then(function(cache) {
            cache.put(event.request, clone);
          });
        }
        return response;
      }).catch(function() {
        // Offline fallback — return index for navigation requests
        if (event.request.mode === 'navigate') {
          return caches.match('/index.html');
        }
      });
    })
  );
});
